name = "etherith"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Next.js Pages configuration
[pages_build_output_dir]
value = ".next"

# Use the Next.js adapter
[adapter]
name = "@cloudflare/next-on-pages"

[vars]
NODE_ENV = "production"

# D1 Database - Cloudflare's native SQLite database
[[d1_databases]]
binding = "DB"
database_name = "etherith-db"
database_id = "042a5e9c-d027-42e9-aeab-cf5302a77af7"

# Enable AI Workers for memory analysis
[ai]
binding = "AI"

# Environment-specific configurations
[env.development]
name = "etherith-dev"
vars = { NODE_ENV = "development" }

[env.production]  
name = "etherith-prod"
vars = { NODE_ENV = "production" }

# KV for caching (optional - can be added later)
# [[kv_namespaces]]
# binding = "CACHE"
# id = ""

# R2 for file storage (optional - can be added later)
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "etherith-storage"