name = "etherith-auth"
main = "index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "etherith-db"
database_id = "042a5e9c-d027-42e9-aeab-cf5302a77af7"

# Environment variables
[vars]
NODE_ENV = "production"
