name = "ai-memory-analyzer"
main = "index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[env.production]
name = "ai-memory-analyzer-prod"

[env.staging]
name = "ai-memory-analyzer-staging"
